
package com.wallet.serviceprovider.dishhome;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DishMediaServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DishMediaServiceHttpPost {


    /**
     * 
     * @param username
     * @return
     *     returns org.tempuri.AuthenticationResult
     */
    @WebMethod(operationName = "Ping")
    @WebResult(name = "Body", partName = "Body")
    public AuthenticationResult ping(
        @WebParam(name = "Username", partName = "Username")
        String username);

    /**
     * 
     * @param username
     */
    @WebMethod(operationName = "PingJSON")
    public void pingJSON(
        @WebParam(name = "Username", partName = "Username")
        String username);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param ani
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "RTNCheck")
    @WebResult(name = "Body", partName = "Body")
    public RTNCheckResponseResult rtnCheck(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "ANI", partName = "ANI")
        String ani,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param ani
     * @param username
     */
    @WebMethod(operationName = "RTNCheckJSON")
    public void rtnCheckJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "ANI", partName = "ANI")
        String ani,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "CustomerIDCheck")
    @WebResult(name = "Body", partName = "Body")
    public RTNCheckResponseResult customerIDCheck(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "CustomerIDCheckJSON")
    public void customerIDCheckJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.PackageInfoResponseResult
     */
    @WebMethod(operationName = "PackageInfo")
    @WebResult(name = "Body", partName = "Body")
    public PackageInfoResponseResult packageInfo(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "PackageInfoJSON")
    public void packageInfoJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param packageName
     * @param username
     * @return
     *     returns org.tempuri.PackageChangeResponseResult
     */
    @WebMethod(operationName = "PackageChange")
    @WebResult(name = "Body", partName = "Body")
    public PackageChangeResponseResult packageChange(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "PackageName", partName = "PackageName")
        String packageName,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param packageName
     * @param username
     */
    @WebMethod(operationName = "PackageChangeJSON")
    public void packageChangeJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "PackageName", partName = "PackageName")
        String packageName,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.BalanceEnquiryResponseResult
     */
    @WebMethod(operationName = "BalanceEnquiry")
    @WebResult(name = "Body", partName = "Body")
    public BalanceEnquiryResponseResult balanceEnquiry(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "BalanceEnquiryJSON")
    public void balanceEnquiryJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.RechargeResponseResult
     */
    @WebMethod(operationName = "Recharge")
    @WebResult(name = "Body", partName = "Body")
    public RechargeResponseResult recharge(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "RechargeAmount", partName = "RechargeAmount")
        String rechargeAmount,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "RechargeJSON")
    public void rechargeJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "RechargeAmount", partName = "RechargeAmount")
        String rechargeAmount,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.GetLanguagesResponseResult
     */
    @WebMethod(operationName = "GetLanguages")
    @WebResult(name = "Body", partName = "Body")
    public GetLanguagesResponseResult getLanguages(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "GetLanguagesJSON")
    public void getLanguagesJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param languageKey
     * @param username
     * @return
     *     returns org.tempuri.UpdateLanguageResponseResult
     */
    @WebMethod(operationName = "UpdateLanguage")
    @WebResult(name = "Body", partName = "Body")
    public UpdateLanguageResponseResult updateLanguage(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "LanguageKey", partName = "LanguageKey")
        String languageKey,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param languageKey
     * @param username
     */
    @WebMethod(operationName = "UpdateLanguageJSON")
    public void updateLanguageJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "CustomerID", partName = "CustomerID")
        String customerID,
        @WebParam(name = "LanguageKey", partName = "LanguageKey")
        String languageKey,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.RechargeResponseResult
     */
    @WebMethod(operationName = "RechargeBySTBIDorCASIDorCHIPID")
    @WebResult(name = "Body", partName = "Body")
    public RechargeResponseResult rechargeBySTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "RechargeAmount", partName = "RechargeAmount")
        String rechargeAmount,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "RechargeBySTBIDorCASIDorCHIPIDJSON")
    public void rechargeBySTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "RechargeAmount", partName = "RechargeAmount")
        String rechargeAmount,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.TransactionHistoryResponseResult
     */
    @WebMethod(operationName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID")
    @WebResult(name = "Body", partName = "Body")
    public TransactionHistoryResponseResult getLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON")
    public void getLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param transactionID
     * @param username
     * @return
     *     returns org.tempuri.CheckTransactionStatusResult
     */
    @WebMethod(operationName = "GetStatusbyTransactionID")
    @WebResult(name = "Body", partName = "Body")
    public CheckTransactionStatusResult getStatusbyTransactionID(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "TransactionID", partName = "TransactionID")
        String transactionID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param transactionID
     * @param username
     */
    @WebMethod(operationName = "GetStatusbyTransactionIDJSON")
    public void getStatusbyTransactionIDJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "TransactionID", partName = "TransactionID")
        String transactionID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "GetCustomerDetailBySTBIDorCASIDorCHIPID")
    @WebResult(name = "Body", partName = "Body")
    public RTNCheckResponseResult getCustomerDetailBySTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "GetCustomerDetailBySTBIDorCASIDorCHIPIDJSON")
    public void getCustomerDetailBySTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", partName = "STBIDorCASIDorCHIPID")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param voucherNumber
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.VoucherResult
     */
    @WebMethod(operationName = "LookupVoucher")
    @WebResult(name = "Body", partName = "Body")
    public VoucherResult lookupVoucher(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "VoucherNumber", partName = "VoucherNumber")
        String voucherNumber,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

    /**
     * 
     * @param password
     * @param voucherNumber
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "LookupVoucherJSON")
    public void lookupVoucherJSON(
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "VoucherNumber", partName = "VoucherNumber")
        String voucherNumber,
        @WebParam(name = "OptionalToken", partName = "OptionalToken")
        String optionalToken);

}
