
package com.wallet.serviceprovider.dishhome;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DishMediaServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DishMediaServiceSoapInterface {


    /**
     * 
     * @param username
     * @return
     *     returns org.tempuri.AuthenticationResult
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PingResponse")
    public AuthenticationResult ping(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param username
     */
    @WebMethod(operationName = "PingJSON", action = "http://tempuri.org/PingJSON")
    @RequestWrapper(localName = "PingJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PingJSON")
    @ResponseWrapper(localName = "PingJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PingJSONResponse")
    public void pingJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param ani
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "RTNCheck", action = "http://tempuri.org/RTNCheck")
    @WebResult(name = "RTNCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RTNCheck", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RTNCheck")
    @ResponseWrapper(localName = "RTNCheckResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RTNCheckResponse")
    public RTNCheckResponseResult rtnCheck(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ANI", targetNamespace = "http://tempuri.org/")
        String ani,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param ani
     * @param username
     */
    @WebMethod(operationName = "RTNCheckJSON", action = "http://tempuri.org/RTNCheckJSON")
    @RequestWrapper(localName = "RTNCheckJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RTNCheckJSON")
    @ResponseWrapper(localName = "RTNCheckJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RTNCheckJSONResponse")
    public void rtnCheckJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ANI", targetNamespace = "http://tempuri.org/")
        String ani,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "CustomerIDCheck", action = "http://tempuri.org/CustomerIDCheck")
    @WebResult(name = "CustomerIDCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CustomerIDCheck", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerIDCheck")
    @ResponseWrapper(localName = "CustomerIDCheckResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerIDCheckResponse")
    public RTNCheckResponseResult customerIDCheck(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "CustomerIDCheckJSON", action = "http://tempuri.org/CustomerIDCheckJSON")
    @RequestWrapper(localName = "CustomerIDCheckJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerIDCheckJSON")
    @ResponseWrapper(localName = "CustomerIDCheckJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerIDCheckJSONResponse")
    public void customerIDCheckJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.PackageInfoResponseResult
     */
    @WebMethod(operationName = "PackageInfo", action = "http://tempuri.org/PackageInfo")
    @WebResult(name = "PackageInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PackageInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageInfo")
    @ResponseWrapper(localName = "PackageInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageInfoResponse")
    public PackageInfoResponseResult packageInfo(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "PackageInfoJSON", action = "http://tempuri.org/PackageInfoJSON")
    @RequestWrapper(localName = "PackageInfoJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageInfoJSON")
    @ResponseWrapper(localName = "PackageInfoJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageInfoJSONResponse")
    public void packageInfoJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param packageName
     * @param username
     * @return
     *     returns org.tempuri.PackageChangeResponseResult
     */
    @WebMethod(operationName = "PackageChange", action = "http://tempuri.org/PackageChange")
    @WebResult(name = "PackageChangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PackageChange", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageChange")
    @ResponseWrapper(localName = "PackageChangeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageChangeResponse")
    public PackageChangeResponseResult packageChange(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "PackageName", targetNamespace = "http://tempuri.org/")
        String packageName,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param packageName
     * @param username
     */
    @WebMethod(operationName = "PackageChangeJSON", action = "http://tempuri.org/PackageChangeJSON")
    @RequestWrapper(localName = "PackageChangeJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageChangeJSON")
    @ResponseWrapper(localName = "PackageChangeJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageChangeJSONResponse")
    public void packageChangeJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "PackageName", targetNamespace = "http://tempuri.org/")
        String packageName,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.BalanceEnquiryResponseResult
     */
    @WebMethod(operationName = "BalanceEnquiry", action = "http://tempuri.org/BalanceEnquiry")
    @WebResult(name = "BalanceEnquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BalanceEnquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BalanceEnquiry")
    @ResponseWrapper(localName = "BalanceEnquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BalanceEnquiryResponse")
    public BalanceEnquiryResponseResult balanceEnquiry(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "BalanceEnquiryJSON", action = "http://tempuri.org/BalanceEnquiryJSON")
    @RequestWrapper(localName = "BalanceEnquiryJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BalanceEnquiryJSON")
    @ResponseWrapper(localName = "BalanceEnquiryJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BalanceEnquiryJSONResponse")
    public void balanceEnquiryJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param customerID
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.RechargeResponseResult
     */
    @WebMethod(operationName = "Recharge", action = "http://tempuri.org/Recharge")
    @WebResult(name = "RechargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Recharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Recharge")
    @ResponseWrapper(localName = "RechargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeResponse")
    public RechargeResponseResult recharge(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "RechargeAmount", targetNamespace = "http://tempuri.org/")
        BigDecimal rechargeAmount,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param customerID
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "RechargeJSON", action = "http://tempuri.org/RechargeJSON")
    @RequestWrapper(localName = "RechargeJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeJSON")
    @ResponseWrapper(localName = "RechargeJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeJSONResponse")
    public void rechargeJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "RechargeAmount", targetNamespace = "http://tempuri.org/")
        BigDecimal rechargeAmount,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.GetLanguagesResponseResult
     */
    @WebMethod(operationName = "GetLanguages", action = "http://tempuri.org/GetLanguages")
    @WebResult(name = "GetLanguagesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLanguagesResponse")
    public GetLanguagesResponseResult getLanguages(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "GetLanguagesJSON", action = "http://tempuri.org/GetLanguagesJSON")
    @RequestWrapper(localName = "GetLanguagesJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLanguagesJSON")
    @ResponseWrapper(localName = "GetLanguagesJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLanguagesJSONResponse")
    public void getLanguagesJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param languageKey
     * @param username
     * @return
     *     returns org.tempuri.UpdateLanguageResponseResult
     */
    @WebMethod(operationName = "UpdateLanguage", action = "http://tempuri.org/UpdateLanguage")
    @WebResult(name = "UpdateLanguageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateLanguage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateLanguage")
    @ResponseWrapper(localName = "UpdateLanguageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateLanguageResponse")
    public UpdateLanguageResponseResult updateLanguage(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "LanguageKey", targetNamespace = "http://tempuri.org/")
        String languageKey,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param customerID
     * @param optionalToken
     * @param languageKey
     * @param username
     */
    @WebMethod(operationName = "UpdateLanguageJSON", action = "http://tempuri.org/UpdateLanguageJSON")
    @RequestWrapper(localName = "UpdateLanguageJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateLanguageJSON")
    @ResponseWrapper(localName = "UpdateLanguageJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateLanguageJSONResponse")
    public void updateLanguageJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "LanguageKey", targetNamespace = "http://tempuri.org/")
        String languageKey,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.RechargeResponseResult
     */
    @WebMethod(operationName = "RechargeBySTBIDorCASIDorCHIPID", action = "http://tempuri.org/RechargeBySTBIDorCASIDorCHIPID")
    @WebResult(name = "RechargeBySTBIDorCASIDorCHIPIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RechargeBySTBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeBySTBIDorCASIDorCHIPID")
    @ResponseWrapper(localName = "RechargeBySTBIDorCASIDorCHIPIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeBySTBIDorCASIDorCHIPIDResponse")
    public RechargeResponseResult rechargeBySTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "RechargeAmount", targetNamespace = "http://tempuri.org/")
        BigDecimal rechargeAmount,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param rechargeAmount
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "RechargeBySTBIDorCASIDorCHIPIDJSON", action = "http://tempuri.org/RechargeBySTBIDorCASIDorCHIPIDJSON")
    @RequestWrapper(localName = "RechargeBySTBIDorCASIDorCHIPIDJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeBySTBIDorCASIDorCHIPIDJSON")
    @ResponseWrapper(localName = "RechargeBySTBIDorCASIDorCHIPIDJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RechargeBySTBIDorCASIDorCHIPIDJSONResponse")
    public void rechargeBySTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "RechargeAmount", targetNamespace = "http://tempuri.org/")
        BigDecimal rechargeAmount,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.TransactionHistoryResponseResult
     */
    @WebMethod(operationName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID", action = "http://tempuri.org/GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID")
    @WebResult(name = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID")
    @ResponseWrapper(localName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDResponse")
    public TransactionHistoryResponseResult getLastPinlessTopupTransactionForSTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON", action = "http://tempuri.org/GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON")
    @RequestWrapper(localName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON")
    @ResponseWrapper(localName = "GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSONResponse")
    public void getLastPinlessTopupTransactionForSTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param transactionID
     * @param username
     * @return
     *     returns org.tempuri.CheckTransactionStatusResult
     */
    @WebMethod(operationName = "GetStatusbyTransactionID", action = "http://tempuri.org/GetStatusbyTransactionID")
    @WebResult(name = "GetStatusbyTransactionIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatusbyTransactionID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusbyTransactionID")
    @ResponseWrapper(localName = "GetStatusbyTransactionIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusbyTransactionIDResponse")
    public CheckTransactionStatusResult getStatusbyTransactionID(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TransactionID", targetNamespace = "http://tempuri.org/")
        int transactionID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param transactionID
     * @param username
     */
    @WebMethod(operationName = "GetStatusbyTransactionIDJSON", action = "http://tempuri.org/GetStatusbyTransactionIDJSON")
    @RequestWrapper(localName = "GetStatusbyTransactionIDJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusbyTransactionIDJSON")
    @ResponseWrapper(localName = "GetStatusbyTransactionIDJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusbyTransactionIDJSONResponse")
    public void getStatusbyTransactionIDJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TransactionID", targetNamespace = "http://tempuri.org/")
        int transactionID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     * @return
     *     returns org.tempuri.RTNCheckResponseResult
     */
    @WebMethod(operationName = "GetCustomerDetailBySTBIDorCASIDorCHIPID", action = "http://tempuri.org/GetCustomerDetailBySTBIDorCASIDorCHIPID")
    @WebResult(name = "GetCustomerDetailBySTBIDorCASIDorCHIPIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerDetailBySTBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailBySTBIDorCASIDorCHIPID")
    @ResponseWrapper(localName = "GetCustomerDetailBySTBIDorCASIDorCHIPIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailBySTBIDorCASIDorCHIPIDResponse")
    public RTNCheckResponseResult getCustomerDetailBySTBIDorCASIDorCHIPID(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param optionalToken
     * @param stbiDorCASIDorCHIPID
     * @param username
     */
    @WebMethod(operationName = "GetCustomerDetailBySTBIDorCASIDorCHIPIDJSON", action = "http://tempuri.org/GetCustomerDetailBySTBIDorCASIDorCHIPIDJSON")
    @RequestWrapper(localName = "GetCustomerDetailBySTBIDorCASIDorCHIPIDJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailBySTBIDorCASIDorCHIPIDJSON")
    @ResponseWrapper(localName = "GetCustomerDetailBySTBIDorCASIDorCHIPIDJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailBySTBIDorCASIDorCHIPIDJSONResponse")
    public void getCustomerDetailBySTBIDorCASIDorCHIPIDJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "STBIDorCASIDorCHIPID", targetNamespace = "http://tempuri.org/")
        String stbiDorCASIDorCHIPID,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param voucherNumber
     * @param optionalToken
     * @param username
     * @return
     *     returns org.tempuri.VoucherResult
     */
    @WebMethod(operationName = "LookupVoucher", action = "http://tempuri.org/LookupVoucher")
    @WebResult(name = "LookupVoucherResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LookupVoucher", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LookupVoucher")
    @ResponseWrapper(localName = "LookupVoucherResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LookupVoucherResponse")
    public VoucherResult lookupVoucher(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "VoucherNumber", targetNamespace = "http://tempuri.org/")
        String voucherNumber,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

    /**
     * 
     * @param password
     * @param voucherNumber
     * @param optionalToken
     * @param username
     */
    @WebMethod(operationName = "LookupVoucherJSON", action = "http://tempuri.org/LookupVoucherJSON")
    @RequestWrapper(localName = "LookupVoucherJSON", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LookupVoucherJSON")
    @ResponseWrapper(localName = "LookupVoucherJSONResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LookupVoucherJSONResponse")
    public void lookupVoucherJSON(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "VoucherNumber", targetNamespace = "http://tempuri.org/")
        String voucherNumber,
        @WebParam(name = "OptionalToken", targetNamespace = "http://tempuri.org/")
        String optionalToken);

}
