//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BusRouteDetailRequest" type="{http://schemas.datacontract.org/2004/07/Utility.API}InputBusRouteDetail"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "busRouteDetailRequest"
})
@XmlRootElement(name = "BusRouteDetail", namespace = "http://tempuri.org/")
public class BusRouteDetail {

    @XmlElement(name = "BusRouteDetailRequest", namespace = "http://tempuri.org/", required = true, nillable = true)
    protected InputBusRouteDetail busRouteDetailRequest;

    /**
     * Gets the value of the busRouteDetailRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InputBusRouteDetail }
     *     
     */
    public InputBusRouteDetail getBusRouteDetailRequest() {
        return busRouteDetailRequest;
    }

    /**
     * Sets the value of the busRouteDetailRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputBusRouteDetail }
     *     
     */
    public void setBusRouteDetailRequest(InputBusRouteDetail value) {
        this.busRouteDetailRequest = value;
    }

}
