//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightDomestic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightDomestic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AirlineCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AirlineName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DepartureTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ArrivalTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AircraftType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Adult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Child" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="FlightId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightClassCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AdultFare" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ChildFare" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="FuelSurcharge" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Tax" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Refundable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FreeBaggage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AdultCommission" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ChildCommission" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="TotalAmount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="TotalCommission" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightDomestic", propOrder = {
    "airlineCode",
    "airlineName",
    "flightDate",
    "flightNo",
    "departure",
    "departureTime",
    "arrival",
    "arrivalTime",
    "aircraftType",
    "adult",
    "child",
    "flightId",
    "flightClassCode",
    "currency",
    "nationality",
    "adultFare",
    "childFare",
    "fuelSurcharge",
    "tax",
    "refundable",
    "freeBaggage",
    "adultCommission",
    "childCommission",
    "totalAmount",
    "totalCommission"
})
public class FlightDomestic {

    @XmlElement(name = "AirlineCode", required = true, nillable = true)
    protected String airlineCode;
    @XmlElement(name = "AirlineName", required = true, nillable = true)
    protected String airlineName;
    @XmlElement(name = "FlightDate", required = true, nillable = true)
    protected String flightDate;
    @XmlElement(name = "FlightNo", required = true, nillable = true)
    protected String flightNo;
    @XmlElement(name = "Departure", required = true, nillable = true)
    protected String departure;
    @XmlElement(name = "DepartureTime", required = true, nillable = true)
    protected String departureTime;
    @XmlElement(name = "Arrival", required = true, nillable = true)
    protected String arrival;
    @XmlElement(name = "ArrivalTime", required = true, nillable = true)
    protected String arrivalTime;
    @XmlElement(name = "AircraftType", required = true, nillable = true)
    protected String aircraftType;
    @XmlElement(name = "Adult")
    protected int adult;
    @XmlElement(name = "Child")
    protected int child;
    @XmlElement(name = "FlightId", required = true, nillable = true)
    protected String flightId;
    @XmlElement(name = "FlightClassCode", required = true, nillable = true)
    protected String flightClassCode;
    @XmlElement(name = "Currency", required = true, nillable = true)
    protected String currency;
    @XmlElement(name = "Nationality", required = true, nillable = true)
    protected String nationality;
    @XmlElement(name = "AdultFare")
    protected double adultFare;
    @XmlElement(name = "ChildFare")
    protected double childFare;
    @XmlElement(name = "FuelSurcharge")
    protected double fuelSurcharge;
    @XmlElement(name = "Tax")
    protected double tax;
    @XmlElement(name = "Refundable", required = true, nillable = true)
    protected String refundable;
    @XmlElement(name = "FreeBaggage", required = true, nillable = true)
    protected String freeBaggage;
    @XmlElement(name = "AdultCommission")
    protected double adultCommission;
    @XmlElement(name = "ChildCommission")
    protected double childCommission;
    @XmlElement(name = "TotalAmount")
    protected double totalAmount;
    @XmlElement(name = "TotalCommission")
    protected double totalCommission;

    /**
     * Gets the value of the airlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * Sets the value of the airlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }

    /**
     * Gets the value of the airlineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineName() {
        return airlineName;
    }

    /**
     * Sets the value of the airlineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineName(String value) {
        this.airlineName = value;
    }

    /**
     * Gets the value of the flightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightDate() {
        return flightDate;
    }

    /**
     * Sets the value of the flightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightDate(String value) {
        this.flightDate = value;
    }

    /**
     * Gets the value of the flightNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNo() {
        return flightNo;
    }

    /**
     * Sets the value of the flightNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNo(String value) {
        this.flightNo = value;
    }

    /**
     * Gets the value of the departure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * Sets the value of the departure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeparture(String value) {
        this.departure = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTime(String value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrival() {
        return arrival;
    }

    /**
     * Sets the value of the arrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrival(String value) {
        this.arrival = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalTime(String value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftType(String value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the adult property.
     * 
     */
    public int getAdult() {
        return adult;
    }

    /**
     * Sets the value of the adult property.
     * 
     */
    public void setAdult(int value) {
        this.adult = value;
    }

    /**
     * Gets the value of the child property.
     * 
     */
    public int getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     * 
     */
    public void setChild(int value) {
        this.child = value;
    }

    /**
     * Gets the value of the flightId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightId() {
        return flightId;
    }

    /**
     * Sets the value of the flightId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightId(String value) {
        this.flightId = value;
    }

    /**
     * Gets the value of the flightClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightClassCode() {
        return flightClassCode;
    }

    /**
     * Sets the value of the flightClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightClassCode(String value) {
        this.flightClassCode = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the adultFare property.
     * 
     */
    public double getAdultFare() {
        return adultFare;
    }

    /**
     * Sets the value of the adultFare property.
     * 
     */
    public void setAdultFare(double value) {
        this.adultFare = value;
    }

    /**
     * Gets the value of the childFare property.
     * 
     */
    public double getChildFare() {
        return childFare;
    }

    /**
     * Sets the value of the childFare property.
     * 
     */
    public void setChildFare(double value) {
        this.childFare = value;
    }

    /**
     * Gets the value of the fuelSurcharge property.
     * 
     */
    public double getFuelSurcharge() {
        return fuelSurcharge;
    }

    /**
     * Sets the value of the fuelSurcharge property.
     * 
     */
    public void setFuelSurcharge(double value) {
        this.fuelSurcharge = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     */
    public double getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     */
    public void setTax(double value) {
        this.tax = value;
    }

    /**
     * Gets the value of the refundable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundable() {
        return refundable;
    }

    /**
     * Sets the value of the refundable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundable(String value) {
        this.refundable = value;
    }

    /**
     * Gets the value of the freeBaggage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeBaggage() {
        return freeBaggage;
    }

    /**
     * Sets the value of the freeBaggage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeBaggage(String value) {
        this.freeBaggage = value;
    }

    /**
     * Gets the value of the adultCommission property.
     * 
     */
    public double getAdultCommission() {
        return adultCommission;
    }

    /**
     * Sets the value of the adultCommission property.
     * 
     */
    public void setAdultCommission(double value) {
        this.adultCommission = value;
    }

    /**
     * Gets the value of the childCommission property.
     * 
     */
    public double getChildCommission() {
        return childCommission;
    }

    /**
     * Sets the value of the childCommission property.
     * 
     */
    public void setChildCommission(double value) {
        this.childCommission = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     */
    public double getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     */
    public void setTotalAmount(double value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the totalCommission property.
     * 
     */
    public double getTotalCommission() {
        return totalCommission;
    }

    /**
     * Sets the value of the totalCommission property.
     * 
     */
    public void setTotalCommission(double value) {
        this.totalCommission = value;
    }

}
