//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetNEAChargeResult" type="{http://schemas.datacontract.org/2004/07/Utility.API}ReturnGetNEACharge" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getNEAChargeResult"
})
@XmlRootElement(name = "GetNEAChargeResponse", namespace = "http://tempuri.org/")
public class GetNEAChargeResponse {

    @XmlElementRef(name = "GetNEAChargeResult", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<ReturnGetNEACharge> getNEAChargeResult;

    /**
     * Gets the value of the getNEAChargeResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReturnGetNEACharge }{@code >}
     *     
     */
    public JAXBElement<ReturnGetNEACharge> getGetNEAChargeResult() {
        return getNEAChargeResult;
    }

    /**
     * Sets the value of the getNEAChargeResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReturnGetNEACharge }{@code >}
     *     
     */
    public void setGetNEAChargeResult(JAXBElement<ReturnGetNEACharge> value) {
        this.getNEAChargeResult = value;
    }

}
