//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InputBusTicketIssue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputBusTicketIssue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BusId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TicketSrlNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BoardingPoint" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SelectedSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="PartnerTxnId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Passengers" type="{http://schemas.datacontract.org/2004/07/Utility.API}ArrayOfBusPassenger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputBusTicketIssue", propOrder = {
    "userName",
    "password",
    "busId",
    "ticketSrlNo",
    "mobileNumber",
    "boardingPoint",
    "selectedSeats",
    "amount",
    "partnerTxnId",
    "passengers"
})
public class InputBusTicketIssue {

    @XmlElement(name = "UserName", required = true, nillable = true)
    protected String userName;
    @XmlElement(name = "Password", required = true, nillable = true)
    protected String password;
    @XmlElement(name = "BusId")
    protected int busId;
    @XmlElement(name = "TicketSrlNo", required = true, nillable = true)
    protected String ticketSrlNo;
    @XmlElement(name = "MobileNumber", required = true, nillable = true)
    protected String mobileNumber;
    @XmlElement(name = "BoardingPoint", required = true, nillable = true)
    protected String boardingPoint;
    @XmlElement(name = "SelectedSeats", required = true, nillable = true)
    protected String selectedSeats;
    @XmlElement(name = "Amount")
    protected double amount;
    @XmlElement(name = "PartnerTxnId", required = true, nillable = true)
    protected String partnerTxnId;
    @XmlElement(name = "Passengers", required = true, nillable = true)
    protected ArrayOfBusPassenger passengers;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the busId property.
     * 
     */
    public int getBusId() {
        return busId;
    }

    /**
     * Sets the value of the busId property.
     * 
     */
    public void setBusId(int value) {
        this.busId = value;
    }

    /**
     * Gets the value of the ticketSrlNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketSrlNo() {
        return ticketSrlNo;
    }

    /**
     * Sets the value of the ticketSrlNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketSrlNo(String value) {
        this.ticketSrlNo = value;
    }

    /**
     * Gets the value of the mobileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * Sets the value of the mobileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNumber(String value) {
        this.mobileNumber = value;
    }

    /**
     * Gets the value of the boardingPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoardingPoint() {
        return boardingPoint;
    }

    /**
     * Sets the value of the boardingPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoardingPoint(String value) {
        this.boardingPoint = value;
    }

    /**
     * Gets the value of the selectedSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedSeats() {
        return selectedSeats;
    }

    /**
     * Sets the value of the selectedSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedSeats(String value) {
        this.selectedSeats = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the partnerTxnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTxnId() {
        return partnerTxnId;
    }

    /**
     * Sets the value of the partnerTxnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTxnId(String value) {
        this.partnerTxnId = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBusPassenger }
     *     
     */
    public ArrayOfBusPassenger getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBusPassenger }
     *     
     */
    public void setPassengers(ArrayOfBusPassenger value) {
        this.passengers = value;
    }

}
