//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InputFlightConfirmDomestic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputFlightConfirmDomestic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OutboundFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InboundFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ContactPerson" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ContactNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Adult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Child" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="PartnerTxnId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AdultPassengers" type="{http://schemas.datacontract.org/2004/07/Utility.API}ArrayOfPassenger"/&gt;
 *         &lt;element name="ChildPassengers" type="{http://schemas.datacontract.org/2004/07/Utility.API}ArrayOfPassenger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputFlightConfirmDomestic", propOrder = {
    "userName",
    "password",
    "outboundFlightId",
    "inboundFlightId",
    "contactPerson",
    "contactEmail",
    "contactNo",
    "adult",
    "child",
    "nationality",
    "currency",
    "amount",
    "partnerTxnId",
    "adultPassengers",
    "childPassengers"
})
public class InputFlightConfirmDomestic {

    @XmlElement(name = "UserName", required = true, nillable = true)
    protected String userName;
    @XmlElement(name = "Password", required = true, nillable = true)
    protected String password;
    @XmlElement(name = "OutboundFlightId", required = true, nillable = true)
    protected String outboundFlightId;
    @XmlElement(name = "InboundFlightId", required = true, nillable = true)
    protected String inboundFlightId;
    @XmlElement(name = "ContactPerson", required = true, nillable = true)
    protected String contactPerson;
    @XmlElement(name = "ContactEmail", required = true, nillable = true)
    protected String contactEmail;
    @XmlElement(name = "ContactNo", required = true, nillable = true)
    protected String contactNo;
    @XmlElement(name = "Adult")
    protected int adult;
    @XmlElement(name = "Child")
    protected int child;
    @XmlElement(name = "Nationality", required = true, nillable = true)
    protected String nationality;
    @XmlElement(name = "Currency", required = true, nillable = true)
    protected String currency;
    @XmlElement(name = "Amount")
    protected double amount;
    @XmlElement(name = "PartnerTxnId", required = true, nillable = true)
    protected String partnerTxnId;
    @XmlElement(name = "AdultPassengers", required = true, nillable = true)
    protected ArrayOfPassenger adultPassengers;
    @XmlElement(name = "ChildPassengers", required = true, nillable = true)
    protected ArrayOfPassenger childPassengers;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the outboundFlightId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundFlightId() {
        return outboundFlightId;
    }

    /**
     * Sets the value of the outboundFlightId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundFlightId(String value) {
        this.outboundFlightId = value;
    }

    /**
     * Gets the value of the inboundFlightId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInboundFlightId() {
        return inboundFlightId;
    }

    /**
     * Sets the value of the inboundFlightId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInboundFlightId(String value) {
        this.inboundFlightId = value;
    }

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPerson(String value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNo() {
        return contactNo;
    }

    /**
     * Sets the value of the contactNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNo(String value) {
        this.contactNo = value;
    }

    /**
     * Gets the value of the adult property.
     * 
     */
    public int getAdult() {
        return adult;
    }

    /**
     * Sets the value of the adult property.
     * 
     */
    public void setAdult(int value) {
        this.adult = value;
    }

    /**
     * Gets the value of the child property.
     * 
     */
    public int getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     * 
     */
    public void setChild(int value) {
        this.child = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the partnerTxnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTxnId() {
        return partnerTxnId;
    }

    /**
     * Sets the value of the partnerTxnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTxnId(String value) {
        this.partnerTxnId = value;
    }

    /**
     * Gets the value of the adultPassengers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPassenger }
     *     
     */
    public ArrayOfPassenger getAdultPassengers() {
        return adultPassengers;
    }

    /**
     * Sets the value of the adultPassengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPassenger }
     *     
     */
    public void setAdultPassengers(ArrayOfPassenger value) {
        this.adultPassengers = value;
    }

    /**
     * Gets the value of the childPassengers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPassenger }
     *     
     */
    public ArrayOfPassenger getChildPassengers() {
        return childPassengers;
    }

    /**
     * Sets the value of the childPassengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPassenger }
     *     
     */
    public void setChildPassengers(ArrayOfPassenger value) {
        this.childPassengers = value;
    }

}
