//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InputFlightSearchDomestic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputFlightSearchDomestic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightMode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SectorFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SectorTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReturnDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Adult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Child" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputFlightSearchDomestic", propOrder = {
    "userName",
    "password",
    "flightMode",
    "sectorFrom",
    "sectorTo",
    "departureDate",
    "returnDate",
    "adult",
    "child",
    "nationality"
})
public class InputFlightSearchDomestic {

    @XmlElement(name = "UserName", required = true, nillable = true)
    protected String userName;
    @XmlElement(name = "Password", required = true, nillable = true)
    protected String password;
    @XmlElement(name = "FlightMode")
    protected int flightMode;
    @XmlElement(name = "SectorFrom", required = true, nillable = true)
    protected String sectorFrom;
    @XmlElement(name = "SectorTo", required = true, nillable = true)
    protected String sectorTo;
    @XmlElement(name = "DepartureDate", required = true, nillable = true)
    protected String departureDate;
    @XmlElement(name = "ReturnDate", required = true, nillable = true)
    protected String returnDate;
    @XmlElement(name = "Adult")
    protected int adult;
    @XmlElement(name = "Child")
    protected int child;
    @XmlElement(name = "Nationality", required = true, nillable = true)
    protected String nationality;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the flightMode property.
     * 
     */
    public int getFlightMode() {
        return flightMode;
    }

    /**
     * Sets the value of the flightMode property.
     * 
     */
    public void setFlightMode(int value) {
        this.flightMode = value;
    }

    /**
     * Gets the value of the sectorFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectorFrom() {
        return sectorFrom;
    }

    /**
     * Sets the value of the sectorFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectorFrom(String value) {
        this.sectorFrom = value;
    }

    /**
     * Gets the value of the sectorTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectorTo() {
        return sectorTo;
    }

    /**
     * Sets the value of the sectorTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectorTo(String value) {
        this.sectorTo = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDate(String value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the returnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnDate() {
        return returnDate;
    }

    /**
     * Sets the value of the returnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnDate(String value) {
        this.returnDate = value;
    }

    /**
     * Gets the value of the adult property.
     * 
     */
    public int getAdult() {
        return adult;
    }

    /**
     * Sets the value of the adult property.
     * 
     */
    public void setAdult(int value) {
        this.adult = value;
    }

    /**
     * Gets the value of the child property.
     * 
     */
    public int getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     * 
     */
    public void setChild(int value) {
        this.child = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

}
