
package com.wallet.serviceprovider.eprabhu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUtility", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUtility {


    /**
     * 
     * @param mobileTopupRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "MobileTopup", action = "http://tempuri.org/IUtility/MobileTopup")
    @WebResult(name = "MobileTopupResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MobileTopup", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.MobileTopup")
    @ResponseWrapper(localName = "MobileTopupResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.MobileTopupResponse")
    public ReturnTransaction mobileTopup(
        @WebParam(name = "MobileTopupRequest", targetNamespace = "http://tempuri.org/")
        InputMobileTopup mobileTopupRequest);

    /**
     * 
     * @param buyRechargeCardsRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "RechargePins", action = "http://tempuri.org/IUtility/RechargePins")
    @WebResult(name = "RechargePinsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RechargePins", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.RechargePins")
    @ResponseWrapper(localName = "RechargePinsResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.RechargePinsResponse")
    public ReturnTransaction rechargePins(
        @WebParam(name = "BuyRechargeCardsRequest", targetNamespace = "http://tempuri.org/")
        InputRechargeCards buyRechargeCardsRequest);

    /**
     * 
     * @param billPaymentRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "BillPayment", action = "http://tempuri.org/IUtility/BillPayment")
    @WebResult(name = "BillPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BillPayment", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BillPayment")
    @ResponseWrapper(localName = "BillPaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BillPaymentResponse")
    public ReturnTransaction billPayment(
        @WebParam(name = "BillPaymentRequest", targetNamespace = "http://tempuri.org/")
        InputBillPayment billPaymentRequest);

    /**
     * 
     * @param checkPolicyRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnCheckPolicy
     */
    @WebMethod(operationName = "CheckPolicy", action = "http://tempuri.org/IUtility/CheckPolicy")
    @WebResult(name = "CheckPolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckPolicy", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.CheckPolicy")
    @ResponseWrapper(localName = "CheckPolicyResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.CheckPolicyResponse")
    public ReturnCheckPolicy checkPolicy(
        @WebParam(name = "CheckPolicyRequest", targetNamespace = "http://tempuri.org/")
        InputCheckPolicy checkPolicyRequest);

    /**
     * 
     * @param insurancePremiumRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "InsurancePremium", action = "http://tempuri.org/IUtility/InsurancePremium")
    @WebResult(name = "InsurancePremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsurancePremium", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.InsurancePremium")
    @ResponseWrapper(localName = "InsurancePremiumResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.InsurancePremiumResponse")
    public ReturnTransaction insurancePremium(
        @WebParam(name = "InsurancePremiumRequest", targetNamespace = "http://tempuri.org/")
        InputInsurancePremium insurancePremiumRequest);

    /**
     * 
     * @param flightSearchDomesticRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnFlightSearchDomestic
     */
    @WebMethod(operationName = "FlightSearchDomestic", action = "http://tempuri.org/IUtility/FlightSearchDomestic")
    @WebResult(name = "FlightSearchDomesticResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FlightSearchDomestic", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightSearchDomestic")
    @ResponseWrapper(localName = "FlightSearchDomesticResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightSearchDomesticResponse")
    public ReturnFlightSearchDomestic flightSearchDomestic(
        @WebParam(name = "FlightSearchDomesticRequest", targetNamespace = "http://tempuri.org/")
        InputFlightSearchDomestic flightSearchDomesticRequest);

    /**
     * 
     * @param flightBookDomesticRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnFlightBookDomestic
     */
    @WebMethod(operationName = "FlightBookDomestic", action = "http://tempuri.org/IUtility/FlightBookDomestic")
    @WebResult(name = "FlightBookDomesticResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FlightBookDomestic", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightBookDomestic")
    @ResponseWrapper(localName = "FlightBookDomesticResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightBookDomesticResponse")
    public ReturnFlightBookDomestic flightBookDomestic(
        @WebParam(name = "FlightBookDomesticRequest", targetNamespace = "http://tempuri.org/")
        InputFlightBookDomestic flightBookDomesticRequest);

    /**
     * 
     * @param flightConfirmDomesticRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "FlightConfirmDomestic", action = "http://tempuri.org/IUtility/FlightConfirmDomestic")
    @WebResult(name = "FlightConfirmDomesticResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FlightConfirmDomestic", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightConfirmDomestic")
    @ResponseWrapper(localName = "FlightConfirmDomesticResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.FlightConfirmDomesticResponse")
    public ReturnTransaction flightConfirmDomestic(
        @WebParam(name = "FlightConfirmDomesticRequest", targetNamespace = "http://tempuri.org/")
        InputFlightConfirmDomestic flightConfirmDomesticRequest);

    /**
     * 
     * @param getTransactionStatusRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "GetTransactionStatus", action = "http://tempuri.org/IUtility/GetTransactionStatus")
    @WebResult(name = "GetTransactionStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTransactionStatus", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetTransactionStatus")
    @ResponseWrapper(localName = "GetTransactionStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetTransactionStatusResponse")
    public ReturnTransaction getTransactionStatus(
        @WebParam(name = "GetTransactionStatusRequest", targetNamespace = "http://tempuri.org/")
        InputGetTransactionStatus getTransactionStatusRequest);

    /**
     * 
     * @param getBalanceRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnGetBalance
     */
    @WebMethod(operationName = "GetBalance", action = "http://tempuri.org/IUtility/GetBalance")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetBalanceResponse")
    public ReturnGetBalance getBalance(
        @WebParam(name = "GetBalanceRequest", targetNamespace = "http://tempuri.org/")
        InputGetBalance getBalanceRequest);

    /**
     * 
     * @param dishHomeBookingRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "DishHomeBooking", action = "http://tempuri.org/IUtility/DishHomeBooking")
    @WebResult(name = "DishHomeBookingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DishHomeBooking", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.DishHomeBooking")
    @ResponseWrapper(localName = "DishHomeBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.DishHomeBookingResponse")
    public ReturnTransaction dishHomeBooking(
        @WebParam(name = "DishHomeBookingRequest", targetNamespace = "http://tempuri.org/")
        InputDishHomeBooking dishHomeBookingRequest);

    /**
     * 
     * @param getGetNEAOfficeCode
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnGetNEAOfficeCode
     */
    @WebMethod(operationName = "GetNEAOfficeCode", action = "http://tempuri.org/IUtility/GetNEAOfficeCode")
    @WebResult(name = "GetNEAOfficeCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNEAOfficeCode", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEAOfficeCode")
    @ResponseWrapper(localName = "GetNEAOfficeCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEAOfficeCodeResponse")
    public ReturnGetNEAOfficeCode getNEAOfficeCode(
        @WebParam(name = "GetGetNEAOfficeCode", targetNamespace = "http://tempuri.org/")
        InputGetNEAOfficeCode getGetNEAOfficeCode);

    /**
     * 
     * @param getNEABillRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnGetNEABill
     */
    @WebMethod(operationName = "GetNEABill", action = "http://tempuri.org/IUtility/GetNEABill")
    @WebResult(name = "GetNEABillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNEABill", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEABill")
    @ResponseWrapper(localName = "GetNEABillResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEABillResponse")
    public ReturnGetNEABill getNEABill(
        @WebParam(name = "GetNEABillRequest", targetNamespace = "http://tempuri.org/")
        InputGetNEABill getNEABillRequest);

    /**
     * 
     * @param getNEAChargeRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnGetNEACharge
     */
    @WebMethod(operationName = "GetNEACharge", action = "http://tempuri.org/IUtility/GetNEACharge")
    @WebResult(name = "GetNEAChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNEACharge", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEACharge")
    @ResponseWrapper(localName = "GetNEAChargeResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetNEAChargeResponse")
    public ReturnGetNEACharge getNEACharge(
        @WebParam(name = "GetNEAChargeRequest", targetNamespace = "http://tempuri.org/")
        InputGetNEACharge getNEAChargeRequest);

    /**
     * 
     * @param checkWlinkAccountRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnCheckWlinkAccount
     */
    @WebMethod(operationName = "CheckWlinkAccount", action = "http://tempuri.org/IUtility/CheckWlinkAccount")
    @WebResult(name = "CheckWlinkAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckWlinkAccount", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.CheckWlinkAccount")
    @ResponseWrapper(localName = "CheckWlinkAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.CheckWlinkAccountResponse")
    public ReturnCheckWlinkAccount checkWlinkAccount(
        @WebParam(name = "CheckWlinkAccountRequest", targetNamespace = "http://tempuri.org/")
        InputCheckWlinkAccount checkWlinkAccountRequest);

    /**
     * 
     * @param busRouteDetailRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnBusRouteDetail
     */
    @WebMethod(operationName = "BusRouteDetail", action = "http://tempuri.org/IUtility/BusRouteDetail")
    @WebResult(name = "BusRouteDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusRouteDetail", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusRouteDetail")
    @ResponseWrapper(localName = "BusRouteDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusRouteDetailResponse")
    public ReturnBusRouteDetail busRouteDetail(
        @WebParam(name = "BusRouteDetailRequest", targetNamespace = "http://tempuri.org/")
        InputBusRouteDetail busRouteDetailRequest);

    /**
     * 
     * @param busDetailSearchRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnBusDetailSearch
     */
    @WebMethod(operationName = "BusDetailSearch", action = "http://tempuri.org/IUtility/BusDetailSearch")
    @WebResult(name = "BusDetailSearchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusDetailSearch", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusDetailSearch")
    @ResponseWrapper(localName = "BusDetailSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusDetailSearchResponse")
    public ReturnBusDetailSearch busDetailSearch(
        @WebParam(name = "BusDetailSearchRequest", targetNamespace = "http://tempuri.org/")
        InputBusDetailSearch busDetailSearchRequest);

    /**
     * 
     * @param busSeatLayoutRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnBusSeatLayout
     */
    @WebMethod(operationName = "BusSeatLayout", action = "http://tempuri.org/IUtility/BusSeatLayout")
    @WebResult(name = "BusSeatLayoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusSeatLayout", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusSeatLayout")
    @ResponseWrapper(localName = "BusSeatLayoutResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusSeatLayoutResponse")
    public ReturnBusSeatLayout busSeatLayout(
        @WebParam(name = "BusSeatLayoutRequest", targetNamespace = "http://tempuri.org/")
        InputBusSeatLayout busSeatLayoutRequest);

    /**
     * 
     * @param busTicketBookRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnBusTicketBook
     */
    @WebMethod(operationName = "BusTicketBook", action = "http://tempuri.org/IUtility/BusTicketBook")
    @WebResult(name = "BusTicketBookResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusTicketBook", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusTicketBook")
    @ResponseWrapper(localName = "BusTicketBookResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusTicketBookResponse")
    public ReturnBusTicketBook busTicketBook(
        @WebParam(name = "BusTicketBookRequest", targetNamespace = "http://tempuri.org/")
        InputBusTicketBook busTicketBookRequest);

    /**
     * 
     * @param busTicketIssueRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "BusTicketIssue", action = "http://tempuri.org/IUtility/BusTicketIssue")
    @WebResult(name = "BusTicketIssueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusTicketIssue", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusTicketIssue")
    @ResponseWrapper(localName = "BusTicketIssueResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.BusTicketIssueResponse")
    public ReturnTransaction busTicketIssue(
        @WebParam(name = "BusTicketIssueRequest", targetNamespace = "http://tempuri.org/")
        InputBusTicketIssue busTicketIssueRequest);

    /**
     * 
     * @param sendSMSRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/IUtility/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.SendSMSResponse")
    public ReturnTransaction sendSMS(
        @WebParam(name = "SendSMSRequest", targetNamespace = "http://tempuri.org/")
        InputSendSMS sendSMSRequest);

    /**
     * 
     * @param getSMSTransactionStatusRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.utility.ReturnTransaction
     */
    @WebMethod(operationName = "GetSMSTransactionStatus", action = "http://tempuri.org/IUtility/GetSMSTransactionStatus")
    @WebResult(name = "GetSMSTransactionStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSMSTransactionStatus", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetSMSTransactionStatus")
    @ResponseWrapper(localName = "GetSMSTransactionStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.wallet.serviceprovider.eprabhu.GetSMSTransactionStatusResponse")
    public ReturnTransaction getSMSTransactionStatus(
        @WebParam(name = "GetSMSTransactionStatusRequest", targetNamespace = "http://tempuri.org/")
        InputGetSMSTransactionStatus getSMSTransactionStatusRequest);

}
