//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnCheckWlinkAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnCheckWlinkAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WlinkUserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PaymentMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BillAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="RenewalPlans" type="{http://schemas.datacontract.org/2004/07/Utility.API}ArrayOfRenewalPlan"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnCheckWlinkAccount", propOrder = {
    "code",
    "message",
    "wlinkUserName",
    "customerName",
    "paymentMessage",
    "billAmount",
    "renewalPlans"
})
public class ReturnCheckWlinkAccount {

    @XmlElement(name = "Code", required = true, nillable = true)
    protected String code;
    @XmlElement(name = "Message", required = true, nillable = true)
    protected String message;
    @XmlElement(name = "WlinkUserName", required = true, nillable = true)
    protected String wlinkUserName;
    @XmlElement(name = "CustomerName", required = true, nillable = true)
    protected String customerName;
    @XmlElement(name = "PaymentMessage", required = true, nillable = true)
    protected String paymentMessage;
    @XmlElementRef(name = "BillAmount", namespace = "http://schemas.datacontract.org/2004/07/Utility.API", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> billAmount;
    @XmlElement(name = "RenewalPlans", required = true, nillable = true)
    protected ArrayOfRenewalPlan renewalPlans;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the wlinkUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWlinkUserName() {
        return wlinkUserName;
    }

    /**
     * Sets the value of the wlinkUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWlinkUserName(String value) {
        this.wlinkUserName = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the paymentMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMessage() {
        return paymentMessage;
    }

    /**
     * Sets the value of the paymentMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMessage(String value) {
        this.paymentMessage = value;
    }

    /**
     * Gets the value of the billAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getBillAmount() {
        return billAmount;
    }

    /**
     * Sets the value of the billAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setBillAmount(JAXBElement<BigDecimal> value) {
        this.billAmount = value;
    }

    /**
     * Gets the value of the renewalPlans property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRenewalPlan }
     *     
     */
    public ArrayOfRenewalPlan getRenewalPlans() {
        return renewalPlans;
    }

    /**
     * Sets the value of the renewalPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRenewalPlan }
     *     
     */
    public void setRenewalPlans(ArrayOfRenewalPlan value) {
        this.renewalPlans = value;
    }

}
