//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:01:18 PM NPT 
//


package com.wallet.serviceprovider.eprabhu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Trip complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trip"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BusId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BusType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VehicleType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NepaliDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MultiDetail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CommissionPercent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InputField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TicketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DepartureTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookedSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UnbookedSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TotalSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RemovableSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AvailableSeats" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="InvisibleSeats" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Ammenities" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trip", propOrder = {
    "busId",
    "operator",
    "busType",
    "vehicleType",
    "nepaliDate",
    "multiDetail",
    "commissionPercent",
    "inputField",
    "ticketPrice",
    "departureTime",
    "bookedSeats",
    "unbookedSeats",
    "totalSeats",
    "removableSeats",
    "availableSeats",
    "invisibleSeats",
    "ammenities"
})
public class Trip {

    @XmlElement(name = "BusId")
    protected int busId;
    @XmlElement(name = "Operator", required = true, nillable = true)
    protected String operator;
    @XmlElement(name = "BusType", required = true, nillable = true)
    protected String busType;
    @XmlElement(name = "VehicleType", required = true, nillable = true)
    protected String vehicleType;
    @XmlElement(name = "NepaliDate", required = true, nillable = true)
    protected String nepaliDate;
    @XmlElement(name = "MultiDetail", required = true, nillable = true)
    protected String multiDetail;
    @XmlElement(name = "CommissionPercent", required = true, nillable = true)
    protected String commissionPercent;
    @XmlElement(name = "InputField", required = true, nillable = true)
    protected String inputField;
    @XmlElement(name = "TicketPrice", required = true, nillable = true)
    protected String ticketPrice;
    @XmlElement(name = "DepartureTime", required = true, nillable = true)
    protected String departureTime;
    @XmlElement(name = "BookedSeats", required = true, nillable = true)
    protected String bookedSeats;
    @XmlElement(name = "UnbookedSeats", required = true, nillable = true)
    protected String unbookedSeats;
    @XmlElement(name = "TotalSeats", required = true, nillable = true)
    protected String totalSeats;
    @XmlElement(name = "RemovableSeats", required = true, nillable = true)
    protected String removableSeats;
    @XmlElement(name = "AvailableSeats")
    protected int availableSeats;
    @XmlElement(name = "InvisibleSeats", required = true, nillable = true)
    protected String invisibleSeats;
    @XmlElement(name = "Ammenities", required = true, nillable = true)
    protected String ammenities;

    /**
     * Gets the value of the busId property.
     * 
     */
    public int getBusId() {
        return busId;
    }

    /**
     * Sets the value of the busId property.
     * 
     */
    public void setBusId(int value) {
        this.busId = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the busType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusType() {
        return busType;
    }

    /**
     * Sets the value of the busType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusType(String value) {
        this.busType = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the nepaliDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNepaliDate() {
        return nepaliDate;
    }

    /**
     * Sets the value of the nepaliDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNepaliDate(String value) {
        this.nepaliDate = value;
    }

    /**
     * Gets the value of the multiDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiDetail() {
        return multiDetail;
    }

    /**
     * Sets the value of the multiDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiDetail(String value) {
        this.multiDetail = value;
    }

    /**
     * Gets the value of the commissionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommissionPercent() {
        return commissionPercent;
    }

    /**
     * Sets the value of the commissionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommissionPercent(String value) {
        this.commissionPercent = value;
    }

    /**
     * Gets the value of the inputField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputField() {
        return inputField;
    }

    /**
     * Sets the value of the inputField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputField(String value) {
        this.inputField = value;
    }

    /**
     * Gets the value of the ticketPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketPrice() {
        return ticketPrice;
    }

    /**
     * Sets the value of the ticketPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketPrice(String value) {
        this.ticketPrice = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTime(String value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the bookedSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookedSeats() {
        return bookedSeats;
    }

    /**
     * Sets the value of the bookedSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookedSeats(String value) {
        this.bookedSeats = value;
    }

    /**
     * Gets the value of the unbookedSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnbookedSeats() {
        return unbookedSeats;
    }

    /**
     * Sets the value of the unbookedSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnbookedSeats(String value) {
        this.unbookedSeats = value;
    }

    /**
     * Gets the value of the totalSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSeats() {
        return totalSeats;
    }

    /**
     * Sets the value of the totalSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSeats(String value) {
        this.totalSeats = value;
    }

    /**
     * Gets the value of the removableSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemovableSeats() {
        return removableSeats;
    }

    /**
     * Sets the value of the removableSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemovableSeats(String value) {
        this.removableSeats = value;
    }

    /**
     * Gets the value of the availableSeats property.
     * 
     */
    public int getAvailableSeats() {
        return availableSeats;
    }

    /**
     * Sets the value of the availableSeats property.
     * 
     */
    public void setAvailableSeats(int value) {
        this.availableSeats = value;
    }

    /**
     * Gets the value of the invisibleSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvisibleSeats() {
        return invisibleSeats;
    }

    /**
     * Sets the value of the invisibleSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvisibleSeats(String value) {
        this.invisibleSeats = value;
    }

    /**
     * Gets the value of the ammenities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmmenities() {
        return ammenities;
    }

    /**
     * Sets the value of the ammenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmmenities(String value) {
        this.ammenities = value;
    }

}
