//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.23 at 02:21:12 PM NPT 
//


package com.wallet.serviceprovider.ntc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authorizationData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorizationData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aliasCategory" type="{http://soapposapi.eservglobal.com/}aliasCategory" minOccurs="0"/&gt;
 *         &lt;element name="aliasName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="aliasPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mvnoId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorizationData", propOrder = {
    "aliasCategory",
    "aliasName",
    "aliasPassword",
    "mvnoId"
})
public class AuthorizationData {

    @XmlSchemaType(name = "string")
    protected AliasCategory aliasCategory;
    protected String aliasName;
    protected String aliasPassword;
    protected Long mvnoId;

    /**
     * Gets the value of the aliasCategory property.
     * 
     * @return
     *     possible object is
     *     {@link AliasCategory }
     *     
     */
    public AliasCategory getAliasCategory() {
        return aliasCategory;
    }

    /**
     * Sets the value of the aliasCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasCategory }
     *     
     */
    public void setAliasCategory(AliasCategory value) {
        this.aliasCategory = value;
    }

    /**
     * Gets the value of the aliasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * Sets the value of the aliasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasName(String value) {
        this.aliasName = value;
    }

    /**
     * Gets the value of the aliasPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasPassword() {
        return aliasPassword;
    }

    /**
     * Sets the value of the aliasPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasPassword(String value) {
        this.aliasPassword = value;
    }

    /**
     * Gets the value of the mvnoId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMvnoId() {
        return mvnoId;
    }

    /**
     * Sets the value of the mvnoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMvnoId(Long value) {
        this.mvnoId = value;
    }

}
