
package com.wallet.serviceprovider.ntc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EndPointInterface", targetNamespace = "http://soapposapi.eservglobal.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class,
})
public interface EndPointInterface {


    /**
     * 
     * @param creditedAgentNotification
     * @param transferredStockList
     * @param creditedAgent
     * @param requesterAuthentication
     * @param requestTag
     * @return
     *     returns com.eservglobal.soapposapi.ERetailCreditResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "eRetailCreditResult", partName = "eRetailCreditResult")
    public ERetailCreditResult eRetailCredit(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "creditedAgent", partName = "creditedAgent")
        AgentIdentifier creditedAgent,
        @WebParam(name = "creditedAgentNotification", partName = "creditedAgentNotification")
        boolean creditedAgentNotification,
        @WebParam(name = "transferredStockList", partName = "transferredStockList")
        TransferredStockList transferredStockList,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param transferredStockList
     * @param requesterAuthentication
     * @param debitedAgentNotification
     * @param requestTag
     * @param debitedAgent
     * @return
     *     returns com.eservglobal.soapposapi.ERetailDebitResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "eRetailDebitResult", partName = "eRetailDebitResult")
    public ERetailDebitResult eRetailDebit(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "debitedAgent", partName = "debitedAgent")
        AgentIdentifier debitedAgent,
        @WebParam(name = "debitedAgentNotification", partName = "debitedAgentNotification")
        boolean debitedAgentNotification,
        @WebParam(name = "transferredStockList", partName = "transferredStockList")
        TransferredStockList transferredStockList,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param rechargeAmount
     * @param productId
     * @param rechargedMsisdn
     * @param requesterAuthentication
     * @param debitedAgentNotification
     * @param requestTag
     * @param debitedAgent
     * @return
     *     returns com.eservglobal.soapposapi.ERetailRechargeResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "eRetailRechargeResult", partName = "eRetailRechargeResult")
    public ERetailRechargeResult eRetailRecharge(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "debitedAgent", partName = "debitedAgent")
        AgentIdentifier debitedAgent,
        @WebParam(name = "rechargedMsisdn", partName = "rechargedMsisdn")
        String rechargedMsisdn,
        @WebParam(name = "debitedAgentNotification", partName = "debitedAgentNotification")
        boolean debitedAgentNotification,
        @WebParam(name = "rechargeAmount", partName = "rechargeAmount")
        long rechargeAmount,
        @WebParam(name = "productId", partName = "productId")
        long productId,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param creditedAgentNotification
     * @param transferredStockList
     * @param creditedAgent
     * @param requesterAuthentication
     * @param debitedAgentNotification
     * @param requestTag
     * @param debitedAgent
     * @return
     *     returns com.eservglobal.soapposapi.ERetailTransferResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "eRetailTransferResult", partName = "eRetailTransferResult")
    public ERetailTransferResult eRetailTransfer(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "debitedAgent", partName = "debitedAgent")
        AgentIdentifier debitedAgent,
        @WebParam(name = "creditedAgent", partName = "creditedAgent")
        AgentIdentifier creditedAgent,
        @WebParam(name = "debitedAgentNotification", partName = "debitedAgentNotification")
        boolean debitedAgentNotification,
        @WebParam(name = "creditedAgentNotification", partName = "creditedAgentNotification")
        boolean creditedAgentNotification,
        @WebParam(name = "transferredStockList", partName = "transferredStockList")
        TransferredStockList transferredStockList,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param productId
     * @param targetAgent
     * @param requesterAuthentication
     * @param requestTag
     * @return
     *     returns com.eservglobal.soapposapi.AgentBalanceResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "agentBalanceResult", partName = "agentBalanceResult")
    public AgentBalanceResult getAgentBalance(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "targetAgent", partName = "targetAgent")
        AgentIdentifier targetAgent,
        @WebParam(name = "productId", partName = "productId")
        String productId,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param targetAgent
     * @param requesterAuthentication
     * @param requestTag
     * @return
     *     returns com.eservglobal.soapposapi.AgentInfoResult
     * @throws WebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "agentInfoResult", partName = "agentInfoResult")
    public AgentInfoResult getAgentInfo(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "targetAgent", partName = "targetAgent")
        AgentIdentifier targetAgent,
        @WebParam(name = "requestTag", partName = "requestTag")
        String requestTag)
        throws WebServiceException_Exception
    ;

    /**
     * 
     * @param requesterAuthentication
     * @param requestTag
     * @param transactionId
     * @param transaction
     * @throws WebServiceException_Exception
     */
    @WebMethod
    public void getTransactionInfo(
        @WebParam(name = "requesterAuthentication", partName = "requesterAuthentication")
        AuthorizationData requesterAuthentication,
        @WebParam(name = "transactionId", partName = "transactionId")
        String transactionId,
        @WebParam(name = "requestTag", mode = WebParam.Mode.INOUT, partName = "requestTag")
        Holder<String> requestTag,
        @WebParam(name = "transaction", mode = WebParam.Mode.OUT, partName = "transaction")
        Holder<GlobalTransaction> transaction)
        throws WebServiceException_Exception
    ;
    
}
