//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 11:09:35 AM NPT 
//


package com.wallet.serviceprovider.ntc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for globalTransaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="globalTransaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="creditedActorId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="creditedActorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="debitedActorId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="debitedActorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="detailTransactionList" type="{http://soapposapi.eservglobal.com/}detailTransactionList" minOccurs="0"/&gt;
 *         &lt;element name="externalTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="medium" type="{http://soapposapi.eservglobal.com/}medium" minOccurs="0"/&gt;
 *         &lt;element name="operationType" type="{http://soapposapi.eservglobal.com/}operationType" minOccurs="0"/&gt;
 *         &lt;element name="requesterActorId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="requesterActorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transactionDateTime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="transactionOperState" type="{http://soapposapi.eservglobal.com/}transactionOperState" minOccurs="0"/&gt;
 *         &lt;element name="iError" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="iErrorInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "globalTransaction", propOrder = {
    "amount",
    "creditedActorId",
    "creditedActorName",
    "debitedActorId",
    "debitedActorName",
    "detailTransactionList",
    "externalTransactionId",
    "medium",
    "operationType",
    "requesterActorId",
    "requesterActorName",
    "transactionDateTime",
    "transactionId",
    "transactionOperState",
    "iError",
    "iErrorInfo"
})
public class GlobalTransaction {

    protected Long amount;
    protected Long creditedActorId;
    protected String creditedActorName;
    protected Long debitedActorId;
    protected String debitedActorName;
    protected DetailTransactionList detailTransactionList;
    protected String externalTransactionId;
    @XmlSchemaType(name = "string")
    protected Medium medium;
    @XmlSchemaType(name = "string")
    protected OperationType operationType;
    protected Long requesterActorId;
    protected String requesterActorName;
    protected Long transactionDateTime;
    protected Long transactionId;
    @XmlSchemaType(name = "string")
    protected TransactionOperState transactionOperState;
    protected Integer iError;
    protected String iErrorInfo;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAmount(Long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the creditedActorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCreditedActorId() {
        return creditedActorId;
    }

    /**
     * Sets the value of the creditedActorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCreditedActorId(Long value) {
        this.creditedActorId = value;
    }

    /**
     * Gets the value of the creditedActorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditedActorName() {
        return creditedActorName;
    }

    /**
     * Sets the value of the creditedActorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditedActorName(String value) {
        this.creditedActorName = value;
    }

    /**
     * Gets the value of the debitedActorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDebitedActorId() {
        return debitedActorId;
    }

    /**
     * Sets the value of the debitedActorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDebitedActorId(Long value) {
        this.debitedActorId = value;
    }

    /**
     * Gets the value of the debitedActorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitedActorName() {
        return debitedActorName;
    }

    /**
     * Sets the value of the debitedActorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitedActorName(String value) {
        this.debitedActorName = value;
    }

    /**
     * Gets the value of the detailTransactionList property.
     * 
     * @return
     *     possible object is
     *     {@link DetailTransactionList }
     *     
     */
    public DetailTransactionList getDetailTransactionList() {
        return detailTransactionList;
    }

    /**
     * Sets the value of the detailTransactionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailTransactionList }
     *     
     */
    public void setDetailTransactionList(DetailTransactionList value) {
        this.detailTransactionList = value;
    }

    /**
     * Gets the value of the externalTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalTransactionId() {
        return externalTransactionId;
    }

    /**
     * Sets the value of the externalTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalTransactionId(String value) {
        this.externalTransactionId = value;
    }

    /**
     * Gets the value of the medium property.
     * 
     * @return
     *     possible object is
     *     {@link Medium }
     *     
     */
    public Medium getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medium }
     *     
     */
    public void setMedium(Medium value) {
        this.medium = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationType }
     *     
     */
    public OperationType getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationType }
     *     
     */
    public void setOperationType(OperationType value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the requesterActorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRequesterActorId() {
        return requesterActorId;
    }

    /**
     * Sets the value of the requesterActorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequesterActorId(Long value) {
        this.requesterActorId = value;
    }

    /**
     * Gets the value of the requesterActorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequesterActorName() {
        return requesterActorName;
    }

    /**
     * Sets the value of the requesterActorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequesterActorName(String value) {
        this.requesterActorName = value;
    }

    /**
     * Gets the value of the transactionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransactionDateTime() {
        return transactionDateTime;
    }

    /**
     * Sets the value of the transactionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransactionDateTime(Long value) {
        this.transactionDateTime = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransactionId(Long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the transactionOperState property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionOperState }
     *     
     */
    public TransactionOperState getTransactionOperState() {
        return transactionOperState;
    }

    /**
     * Sets the value of the transactionOperState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionOperState }
     *     
     */
    public void setTransactionOperState(TransactionOperState value) {
        this.transactionOperState = value;
    }

    /**
     * Gets the value of the iError property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIError() {
        return iError;
    }

    /**
     * Sets the value of the iError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIError(Integer value) {
        this.iError = value;
    }

    /**
     * Gets the value of the iErrorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIErrorInfo() {
        return iErrorInfo;
    }

    /**
     * Sets the value of the iErrorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIErrorInfo(String value) {
        this.iErrorInfo = value;
    }

}
