//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 11:09:35 AM NPT 
//


package com.wallet.serviceprovider.ntc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for medium.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="medium"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WEB"/&gt;
 *     &lt;enumeration value="SOAP"/&gt;
 *     &lt;enumeration value="SMS"/&gt;
 *     &lt;enumeration value="USSD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "medium")
@XmlEnum
public enum Medium {

    WEB,
    SOAP,
    SMS,
    USSD;

    public String value() {
        return name();
    }

    public static Medium fromValue(String v) {
        return valueOf(v);
    }

}
