//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 11:09:35 AM NPT 
//


package com.wallet.serviceprovider.ntc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="operationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RECHARGE_VLOAD_POS"/&gt;
 *     &lt;enumeration value="RECHARGE_ELOAD_POS"/&gt;
 *     &lt;enumeration value="RECHARGE_EVOUCHER"/&gt;
 *     &lt;enumeration value="VOUCHER_ON_DEMAND"/&gt;
 *     &lt;enumeration value="POS_ACCT_TRANSFER"/&gt;
 *     &lt;enumeration value="POS_INCENTIVE"/&gt;
 *     &lt;enumeration value="CASH_IN"/&gt;
 *     &lt;enumeration value="CASH_OUT_REQUEST"/&gt;
 *     &lt;enumeration value="P2P_TRANSFER"/&gt;
 *     &lt;enumeration value="REVERSE_TRANSACTION"/&gt;
 *     &lt;enumeration value="POS_RECHARGE_MLOAD"/&gt;
 *     &lt;enumeration value="REMITTANCE"/&gt;
 *     &lt;enumeration value="CREDIT_REMITTANCE"/&gt;
 *     &lt;enumeration value="REMITTANCE_CREDIT"/&gt;
 *     &lt;enumeration value="BILL_PAYMENT"/&gt;
 *     &lt;enumeration value="COMMISSION"/&gt;
 *     &lt;enumeration value="BILL_PAYMENT_COMMISSION"/&gt;
 *     &lt;enumeration value="CASH_IN_COMMISSION"/&gt;
 *     &lt;enumeration value="CASH_OUT_COMMISSION"/&gt;
 *     &lt;enumeration value="P2P_TRANSFER_COMMISSION"/&gt;
 *     &lt;enumeration value="RECHARGE_MLOAD_COMMISSION"/&gt;
 *     &lt;enumeration value="P2P_TRANSFER_INCENTIVE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "operationType")
@XmlEnum
public enum OperationType {

    RECHARGE_VLOAD_POS("RECHARGE_VLOAD_POS"),
    RECHARGE_ELOAD_POS("RECHARGE_ELOAD_POS"),
    RECHARGE_EVOUCHER("RECHARGE_EVOUCHER"),
    VOUCHER_ON_DEMAND("VOUCHER_ON_DEMAND"),
    POS_ACCT_TRANSFER("POS_ACCT_TRANSFER"),
    POS_INCENTIVE("POS_INCENTIVE"),
    CASH_IN("CASH_IN"),
    CASH_OUT_REQUEST("CASH_OUT_REQUEST"),
    @XmlEnumValue("P2P_TRANSFER")
    P_2_P_TRANSFER("P2P_TRANSFER"),
    REVERSE_TRANSACTION("REVERSE_TRANSACTION"),
    POS_RECHARGE_MLOAD("POS_RECHARGE_MLOAD"),
    REMITTANCE("REMITTANCE"),
    CREDIT_REMITTANCE("CREDIT_REMITTANCE"),
    REMITTANCE_CREDIT("REMITTANCE_CREDIT"),
    BILL_PAYMENT("BILL_PAYMENT"),
    COMMISSION("COMMISSION"),
    BILL_PAYMENT_COMMISSION("BILL_PAYMENT_COMMISSION"),
    CASH_IN_COMMISSION("CASH_IN_COMMISSION"),
    CASH_OUT_COMMISSION("CASH_OUT_COMMISSION"),
    @XmlEnumValue("P2P_TRANSFER_COMMISSION")
    P_2_P_TRANSFER_COMMISSION("P2P_TRANSFER_COMMISSION"),
    RECHARGE_MLOAD_COMMISSION("RECHARGE_MLOAD_COMMISSION"),
    @XmlEnumValue("P2P_TRANSFER_INCENTIVE")
    P_2_P_TRANSFER_INCENTIVE("P2P_TRANSFER_INCENTIVE");
    private final String value;

    OperationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperationType fromValue(String v) {
        for (OperationType c: OperationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
