
package com.wallet.serviceprovider.ntc;

import javax.xml.ws.WebFault;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WebServiceException", targetNamespace = "http://soapposapi.eservglobal.com/")
public class WebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WebServiceException_Exception(String message, WebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WebServiceException_Exception(String message, WebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.eservglobal.soapposapi.WebServiceException
     */
    public WebServiceException getFaultInfo() {
        return faultInfo;
    }

}
